version: "2"

run:
  concurrency: 4
  tests: true
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    # - dogsled
    - dupl
    # - errcheck
    - gochecknoinits
    - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - gosec
    # - govet
    - ineffassign
    - misspell
    - nakedret
    # - prealloc
    # - revive
    # - staticcheck
    - unconvert
    # - unparam
    # - unused
    - whitespace

formatters:
  enable:
    - gofumpt
    - goimports
    - gci

issues:
  exclude-rules:
    - path: "test/e2e"
      linters:
        - goconst  # constants here add no value, so we skip goconst only for test/e2e.
