# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

report_sizes: true

builds:
  - id: uncloud
    main: ./cmd/uncloud
    binary: uncloud
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      #- windows
    goarch:
      - amd64
      - arm64

  - id: uncloudd
    main: ./cmd/uncloudd
    binary: uncloudd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: uncloud
    builds:
      - uncloud
    format: gz
    name_template: >-
      {{ .Binary }}_
      {{- if eq .Os "darwin"}}macos
      {{- else}}{{.Os}}{{end}}_
      {{- .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

  - id: uncloudd
    builds:
      - uncloudd
    format: gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: uncloud
    description: "Uncloud CLI"
    homepage: "https://uncloud.run"
    install: |
      bin.install "uncloud"
    skip_upload: false
    repository:
      owner: psviderski
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN_HOMEBREW_TAP }}"
